/**
 * Brand partial build library
 *
 * Generates pongo2 brand partials from settings and SVG sources.
 * Used by scripts/post-web-build.js.
 */

/**
 * HTML entity escape map for text contexts.
 * @type {Record<string, string>}
 */
const ATTR_ESCAPES = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
}

/**
 * Escape a string for safe inclusion in HTML text context.
 * @param {string} s - The string to escape
 * @returns {string} HTML-escaped string
 */
function escapeHtmlText(s) {
  return String(s).replace(/[&<>"']/g, c => ATTR_ESCAPES[c])
}

/**
 * Canonical static brand file names that get copied to bskyweb/static.
 * @type {string[]}
 */
const BRAND_STATIC_FILES = [
  'favicon-16x16.png',
  'favicon-32x32.png',
  'favicon.png',
  'apple-touch-icon.png',
  'safari-pinned-tab.svg',
  'social-card-default.png',
  'social-card-default-gradient.png',
]

const GENERATED_NOTICE =
  '{# GENERATED by scripts/post-web-build.js — do not edit by hand. #}'

/**
 * Build the brand title fragment (included inside the <title> tag).
 *
 * The app name is HTML-escaped for safe text-context inclusion.
 *
 * @param {Object} settings - AppSettings object with brand fields
 * @returns {string} The title fragment content
 */
function buildBrandTitle(settings) {
  return escapeHtmlText(settings.APP_NAME)
}

/**
 * Build the brand splash fragment (included inside the #splash element).
 *
 * lightSvg/darkSvg are trusted raw SVG source and injected verbatim.
 *
 * @param {string} lightSvg - Raw SVG content for the light theme splash
 * @param {string} darkSvg - Raw SVG content for the dark theme splash
 * @returns {string} The splash fragment markup
 */
function buildBrandSplash(lightSvg, darkSvg) {
  return `${GENERATED_NOTICE}
<span class="splash-light">${lightSvg}</span>
<span class="splash-dark">${darkSvg}</span>
`
}

/**
 * Build the brand meta fragment (included in <head>).
 *
 * Text-context values are HTML-escaped. The theme-color tag omits its content
 * attribute entirely when THEME_COLOR is empty (matches the legacy output).
 *
 * @param {Object} settings - AppSettings object with brand fields
 * @returns {string} The meta/link fragment markup
 */
function buildBrandMeta(settings) {
  const applicationName = escapeHtmlText(settings.APPLICATION_NAME)
  const ogSiteName = escapeHtmlText(settings.OG_SITE_NAME)
  const twitter = escapeHtmlText(settings.TWITTER_HANDLE)
  const maskColor = escapeHtmlText(settings.MASK_ICON_COLOR)
  const themeColor = escapeHtmlText(settings.THEME_COLOR)

  // Build theme-color meta tag - omit content attribute when empty
  const themeColorMeta =
    themeColor === ''
      ? '<meta name="theme-color">'
      : `<meta name="theme-color" content="${themeColor}">`

  return `${GENERATED_NOTICE}
<link rel="mask-icon" href="{{ staticCDNHost }}/static/safari-pinned-tab.svg" color="${maskColor}">
${themeColorMeta}
<meta name="application-name" content="${applicationName}">
<meta property="og:site_name" content="${ogSiteName}">
<meta name="twitter:site" content="${twitter}" />
`
}

module.exports = {
  escapeHtmlText,
  buildBrandTitle,
  buildBrandSplash,
  buildBrandMeta,
  BRAND_STATIC_FILES,
}
